############################################################
# @author Elias De Hondt, Kobe Wijnants, Quinten Willekens #
# @since 18/09/2024                                        #
############################################################

# Defining the API version for standard Kubernetes resources.
apiVersion: v1

# Specifies the creation of a ServiceAccount.
kind: ServiceAccount

# Metadata section - used to configure the name and namespace for the ServiceAccount.
metadata:
  name: admin-user                    # Name of the ServiceAccount, designated as 'admin-user'.
  namespace: kubernetes-dashboard     # The namespace in which this ServiceAccount is created (specific to kubernetes-dashboard).

---

# Again, defining the API version for standard Kubernetes resources.
apiVersion: v1

# Specifies the creation of a Secret.
kind: Secret

# Metadata section - used to configure the name of the Secret and any additional annotations.
metadata:
  name: admin-user-token              # Name of the Secret associated with the admin-user ServiceAccount.
  annotations:
    kubernetes.io/service-account.name: admin-user  # Annotation linking this Secret to the 'admin-user' ServiceAccount.

# Specifies that this Secret is of type 'service-account-token', automatically generated to store the token for authentication.
type: kubernetes.io/service-account-token
